#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh

# When run without any option,
## "xrandr" shows the names of different outputs available on the system (VGA-1, HDMI-1, etc.)
## and resolutions available on each, with a * after the current one and a + after the preferred one.
bspc monitor -d I II III IV V VI VII VIII IX X


bspc config border_width        1
bspc config window_gap          5
bspc config focus_follows_pointer true
bspc config ignore_ewmh_focus true
bspc config focused_border_color "#ff79c6"
bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false

# Use the command "xprop WM_CLASS" to make sure you are using the proper string.
## eg. Chromium
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a rofi manage=off
